# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('conf_text_type', models.CharField(choices=[('txt', 'Plain Text'), ('html', 'Html')], default='txt', max_length=500)),
                ('text', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='about')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sub_slogan', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='benefit')),
                ('dataItem', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('dataItem', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('dataItem', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('conf_text_type', models.CharField(choices=[('txt', 'Plain Text'), ('html', 'Html')], default='txt', max_length=500)),
                ('text', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='insurance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sub_slogan', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='insurancetype')),
                ('dataItem', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sub_slogan', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='steps')),
                ('dataItem', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sub_slogan', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='whychose')),
                ('dataItem', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCodeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('conf_text_type', models.CharField(choices=[('txt', 'Plain Text'), ('html', 'Html')], default='txt', max_length=500)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
