# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttext',
            name='sub_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurancetext',
            name='sub_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
