# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_termsandprivacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsandprivacy',
            old_name='text',
            new_name='sub_text',
        ),
    ]
