# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20171023_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandprivacy',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
