# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171023_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hg_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hg_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hg_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
