# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171030_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteformdatamodel',
            old_name='CSD',
            new_name='csd',
        ),
        migrations.RenameField(
            model_name='siteformdatamodel',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='siteformdatamodel',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='siteformdatamodel',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='siteformdatamodel',
            old_name='type',
            new_name='policy_type',
        ),
        migrations.RenameField(
            model_name='siteformdatamodel',
            old_name='zipcode',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='siteformdatamodel',
            name='house_income',
        ),
        migrations.AddField(
            model_name='siteformdatamodel',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteformdatamodel',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
