# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171102_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteformdatamodel',
            name='attempt_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='siteformdatamodel',
            name='attempt_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteformdatamodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteformdatamodel',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
