# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180312_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteformdatamodel',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
