# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180322_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteformdatamodel',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='siteformdatamodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteformdatamodel',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Family', 'Family')], max_length=50, null=True),
        ),
    ]
