# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180403_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(choices=[('index', 'Home'), ('privacy', 'Privacy'), ('terms', 'Terms'), ('thanks', 'Thanks')], max_length=100),
        ),
    ]
