# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180404_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteformdatamodel',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
