# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_siteformdatamodel_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
