#!/bin/bash

DBNAME="site_manager_db"
DBUSER="siteuser"
DBPASS="password"

sudo -u postgres bash << EOF
psql --command "CREATE USER $DBUSER WITH SUPERUSER PASSWORD '$DBPASS';" && createdb -O $DBUSER $DBNAME
EOF


